AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: lambdabot

Resources:
  lambdabot:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: nodejs6.10
      Events:
        Index:
          Type: Api
          Properties:
            Path: /
            Method: get
