AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: lambdabot

Resources:
  lambdabot_gateway:
    Type: AWS::Serverless::Api
    Properties:
      Variables:
         lambdabot_lambda: !Ref lambdabot_lambda

  lambdabot_lambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: nodejs6.10
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref lambdabot_gateway
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref lambdabot_gateway
            Path: /{proxy+}
            Method: ANY
